### ISSUE TITLE
ModuleImportError: No class inheriting "napalm_base.base.NetworkDriver" found in "napalm_mos"

### ISSUE THREAD

**Issue by MattHoy** [napalm-automation-community/napalm-mos#1]
Hi, I suspect this is me configuring something incorrectly but I wasn't too sure how else to ask, 

We already manage IOS and EOS devices with Salt and Napalm and I was hoping to use your module to have it also manage MOS devices. I have no problem connecting directly via python, but when called from salt-proxy it bombs:
[CRITICAL] Unexpected error while connecting to localhost
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 864, in _connect_minion
    yield minion.connect_master(failed=failed)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 214, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1042, in connect_master
    yield self._post_master_init(master)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 214, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 879, in run
    yielded = self.gen.send(value)
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 3168, in _post_master_init
    proxy_init_fn(self.opts)
  File "/usr/lib/python2.7/site-packages/salt/proxy/napalm.py", line 181, in init
    NETWORK_DEVICE.update(salt.utils.napalm.get_device(opts))
  File "/usr/lib/python2.7/site-packages/salt/utils/napalm.py", line 309, in get_device
    _driver_ = provider_lib.get_network_driver(network_device.get('DRIVER_NAME'))
  File "/usr/lib/python2.7/site-packages/napalm_base/__init__.py", line 114, in get_network_driver
    .format(install_name=module_install_name))
ModuleImportError: No class inheriting "napalm_base.base.NetworkDriver" found in "napalm_mos".

**Comment by bewing** [comment]
napalm_mos is written for napalm>=2.0.0.  Per @mirceaulinic, you can make salt use napalm 2.0 by installing `napalm_base>=1`, and also installing `napalm>=2`
